### ISSUE TITLE
Cannot read properties of undefined (reading 'load')

### ISSUE THREAD

**Issue by olga-cr** [evecalm/truncate-html#40]
Started running into this issue with pretty much any payload. E.g.
`const truncated = truncate('<p><img src="xxx.jpg">Hello from earth!</p>', 2, { byWords: true });`
throws an error. Stacktrace:

```
uncaughtException: Cannot read properties of undefined (reading 'load')
TypeError: Cannot read properties of undefined (reading 'load')
    at $742b69707032309e$var$truncate (/home/user/repo/packages/api/node_modules/truncate-html/dist/truncate.cjs.js:154:55)
```

Looks like the line in question is `$ = (0, ($parcel$interopDefault($1J0WF$cheerio))).load(`${html}`, {`.
Downgrading to 1.1.1 does not seem to fix this.

**Comment by oe** [comment]
Please upgrade to version `v1.1.2` and make sure that the version of `cheerio` is `1.0.0-rc.12` (check with `yarn why cheerio`, or check the node_modules folder to verify).

It's a problem caused by the stable release of cheerio v1.0.0. related links: #39 , [release v1.1.2](https://github.com/oe/truncate-html/releases/tag/v1.1.2)

**Comment by oe** [comment]
If this problem persists, please reopen the issue. In the meantime, kindly close the current instance.
